version: '3'
services:

    # PHP Service
    codeigniter4-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: codeigniter4-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
        networks:
            - codeigniter4-app-network

    # NGINX Service
    codeigniter4-webserver:
        image: nginx:alpine
        container_name: codeigniter4-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - codeigniter4-app-network

    # MySQL Service
    codeigniter4-mariadb:
        image: mariadb:latest
        container_name: codeigniter4-mariadb
        hostname: mariadb
        restart: unless-stopped
        tty: true
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: hungna
        volumes:
            - codeigniter4-db-data:/var/lib/mysql
            - ./docker/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf
        networks:
            - codeigniter4-app-network

    # PHP MyAdmin Service
    codeigniter4-phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: codeigniter4-phpmyadmin
        restart: unless-stopped
        depends_on:
            - codeigniter4-mariadb
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=hungna
        ports:
            - "3380:80"
        networks:
            - codeigniter4-app-network

#Docker Networks
networks:
    codeigniter4-app-network:
        driver: bridge

#Volumes
volumes:
    codeigniter4-db-data:
        driver: local
